import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Typography } from 'antd';
import { LocaleFormatter } from '@/locales';
const { Title, Paragraph } = Typography;
const div = _jsx("div", { style: { height: 200 }, children: "2333" }, void 0);
const DocumentationPage = () => {
    return (_jsx("div", { children: _jsxs(Typography, { className: "innerText", children: [_jsx(Title, { children: _jsx(LocaleFormatter, { id: "app.documentation.introduction.title" }, void 0) }, void 0), _jsx(Paragraph, { children: _jsx(LocaleFormatter, { id: "app.documentation.introduction.description" }, void 0) }, void 0), _jsx(Title, { children: _jsx(LocaleFormatter, { id: "app.documentation.catalogue.title" }, void 0) }, void 0), _jsx(Paragraph, { children: _jsx(LocaleFormatter, { id: "app.documentation.catalogue.description" }, void 0) }, void 0), _jsx(Paragraph, { children: _jsxs("ul", { children: [_jsx("li", { children: _jsx("a", { href: "#layout", children: _jsx(LocaleFormatter, { id: "app.documentation.catalogue.list.layout" }, void 0) }, void 0) }, void 0), _jsx("li", { children: _jsx("a", { href: "#routes", children: _jsx(LocaleFormatter, { id: "app.documentation.catalogue.list.routes" }, void 0) }, void 0) }, void 0), _jsx("li", { children: _jsx("a", { href: "#request", children: _jsx(LocaleFormatter, { id: "app.documentation.catalogue.list.request" }, void 0) }, void 0) }, void 0), _jsx("li", { children: _jsx("a", { href: "#theme", children: _jsx(LocaleFormatter, { id: "app.documentation.catalogue.list.theme" }, void 0) }, void 0) }, void 0), _jsx("li", { children: _jsx("a", { href: "#typescript", children: _jsx(LocaleFormatter, { id: "app.documentation.catalogue.list.typescript" }, void 0) }, void 0) }, void 0), _jsx("li", { children: _jsx("a", { href: "#international", children: _jsx(LocaleFormatter, { id: "app.documentation.catalogue.list.international" }, void 0) }, void 0) }, void 0)] }, void 0) }, void 0), _jsx(Title, { id: "layout", level: 2, children: _jsx(LocaleFormatter, { id: "app.documentation.catalogue.list.layout" }, void 0) }, void 0), _jsx(Paragraph, { children: div }, void 0), _jsx(Title, { id: "routes", level: 2, children: _jsx(LocaleFormatter, { id: "app.documentation.catalogue.list.routes" }, void 0) }, void 0), _jsx(Paragraph, { children: div }, void 0), _jsx(Title, { id: "request", level: 2, children: _jsx(LocaleFormatter, { id: "app.documentation.catalogue.list.request" }, void 0) }, void 0), _jsx(Paragraph, { children: div }, void 0), _jsx(Title, { id: "theme", level: 2, children: _jsx(LocaleFormatter, { id: "app.documentation.catalogue.list.theme" }, void 0) }, void 0), _jsx(Paragraph, { children: div }, void 0), _jsx(Title, { id: "typescript", level: 2, children: _jsx(LocaleFormatter, { id: "app.documentation.catalogue.list.typescript" }, void 0) }, void 0), _jsx(Paragraph, { children: div }, void 0), _jsx(Title, { id: "international", level: 2, children: _jsx(LocaleFormatter, { id: "app.documentation.catalogue.list.international" }, void 0) }, void 0), _jsx(Paragraph, { children: div }, void 0)] }, void 0) }, void 0));
};
export default DocumentationPage;
